micronaut:

  server:
    port: 8632

  metrics:
    enabled: true
    export:
      prometheus:
        step: PT2s
        descriptions: false

  http:
    services:
      read-timeout: 30s
      ngsi:
        path: ngsi-ld/v1
        url: http://localhost:1026
        read-timeout: 30
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
---
endpoints:
  metrics:
    enabled: true
  health:
    enabled: true

---
loggers:
  levels:
    ROOT: TRACE

---
general:
  contextUrl: https://smartdatamodels.org/context.jsonld
  serverHost: http://localhost:8632