micronaut:
  application:
    name: ${project.artifactId}

  caches:
    entities:
      maximumSize: 1000
      # enough to not call twice in one call, but would prevent conflicting writes
      expire-after-write: 2s
      expire-after-access: 2s

  server:
    port: 8633

  metrics:
    enabled: true
    export:
      prometheus:
        step: PT2s
        descriptions: false

  http:
    services:
      read-timeout: 30s
      ngsi:
        path: ngsi-ld/v1
        url: http://localhost:1026
        read-timeout: 30
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
---
endpoints:
  metrics:
    enabled: true
  health:
    enabled: true

---
loggers:
  levels:
    ROOT: TRACE

---
general:
  ngsildOrQueryValue: ","
  ngsildOrQueryKey: ","
  encloseQuery: false
  contextUrl: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
  serverHost: http://localhost:8632
