name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  push:
    branches:
      - tests
      - ServiceInventory-Implementation

concurrency:
  # Only cancel jobs for PR updates
  group: test-it-${{ github.ref }}
  cancel-in-progress: true

jobs:
  it:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        module: [ customer-bill-management, customer-management, party-catalog, party-role, product-catalog, product-inventory, product-ordering-management, resource-catalog, resource-function-activation, resource-inventory, service-catalog, service-inventory ]
        # only test scorpio for speed up, orion is currently not really used with the tmforum
        broker: [ scorpio ]
        cache: [ in-memory, redis ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk

      - name: Ensure br_netfilter is enabled.
        run: |
          sudo modprobe br_netfilter

      - name: Execute tests
        id: test
        continue-on-error: true
        run: |
          mvn clean test integration-test verify --projects common,resource-shared-models,customer-shared-models,service-shared-models,product-shared-models,${{matrix.module}} -Dbroker=${{matrix.broker}} -Dcache=${{matrix.cache}}

      - name: Archive coverage
        if: matrix.broker == 'scorpio' && matrix.cache == 'in-memory'
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.module}}
          path: |
            ${{matrix.module}}/target/site/jacoco/jacoco.xml

  unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [ common, resource-shared-models, customer-shared-models, service-shared-models, product-shared-models ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk

      - name: Execute tests
        id: test
        run: |
          mvn clean test --projects common,resource-shared-models,customer-shared-models,service-shared-models,product-shared-models,${{matrix.module}}

      - name: Archive coverage
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.module}}
          path: |
            ${{matrix.module}}/target/site/jacoco/jacoco.xml

  upload-report:
    needs: [ "it","unit" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: jacoco-merge-dir


      - name: Merge and Submit report
        run: |
          ls -R jacoco-merge-dir
          mvn jacoco:merge jacoco:report coveralls:report -Dcoveralls.token=${{ secrets.COVERALLS_TOKEN }} -Djacoco.mergeDir=jacoco-merge-dir -Preport-coveralls
