name: Test different brokers

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  push:
    branches:
      - tests

concurrency:
  # Only cancel jobs for PR updates
  group: test-it-${{ github.ref }}
  cancel-in-progress: true

jobs:
  it:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [ customer-bill-management, customer-management, party-catalog, party-role, product-catalog, product-inventory, product-ordering-management, resource-catalog, resource-function-activation, resource-inventory, service-catalog ]
        # only test scorpio for speed up, orion is currently not really used with the tmforum
        broker: [scorpio]
        cache: [in-memory, redis]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk

      - name: Execute tests
        id: test
        run: |
          mvn clean test integration-test verify --projects common,resource-shared-models,customer-shared-models,service-shared-models,product-shared-models,${{matrix.module}} -Dbroker=${{matrix.broker}} -Dcache=${{matrix.cache}}

      - name: Archive coverage
        if: matrix.broker == 'scorpio' && matrix.cache == 'in-memory'
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.module}}-report
          path: |
            ${{matrix.module}}/target/jacoco.exec

  upload-report:
    needs: ["it"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk

      - name: Compile
        run: |
          mvn clean install -DskiptTests -DskipITs

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: jacoco-merge-dir


      - name: Merge and Submit report
        run: |
          mvn jacoco:merge jacoco:report coveralls:report -Dcoveralls.token=${{ secrets.COVERALLS_TOKEN }} -Djacoco.mergeDir=jacoco-merge-dir -Preport-coveralls
